name: "Teddycloud"
version: "latest"
slug: folder
description: >-
  "Teddycloud for Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/toniebox-reverse-engineering/teddycloud"
slug: "teddycloud"
ports:
  80/tcp: 80
  443/tcp: 443
map:
  - type: share
    read_only: False
  - type: ssl
  - type: all_addon_configs
    read_only: False
image: "jaycuppp/teddycloud"
host_network: True
